name: Run Appium Tests 
on: 
 workflow_dispatch:
 push:
jobs:
  run-appium-tests:
    runs-on: ubuntu-latest
    steps:
        - name: Code Checkout
          uses: actions/checkout@v4
        - name: Setup Node
          uses: actions/setup-node@v1
          with:
            node-version: 18
        - name: Install
          run: npm install
        - name: Run Tests
          # env:
          #   BROWSERSTACK_USERNAME: ${{ secrets.BS_NAME }}
          #   BROWSERSTACK_ACCESS_KEY: ${{ secrets.BS_KEY }}
          run: npx wdio run wdio.android.bs.conf.js --spec ./test/specs/android.ts 
        - name: Log Results on Test Failure
          uses: actions/upload-artifact@v1
          if: failure()
          with:
            name: logs
            path: logs

  send-slack-notification:
   needs: [run-appium-tests] # Wait for both cypress-run and performance-tests to complete
   if: always() # Always run the Slack notification job regardless of the status of previous jobs
   runs-on: ubuntu-latest
   name: Send Slack Notification
   steps:
    #  - name: Combine job outputs
    #    id: combine-outputs
    #    run: |
    #      echo "cypress-status=${{ needs.cypress-run.result }}" >> $GITHUB_OUTPUT
    #      echo "performance-tests-status=${{ needs.performance-tests.result }}" >> $GITHUB_OUTPUT
    #      echo "lighthouse-tests-status=${{ needs.lighthouse-tests.result }}" >> $GITHUB_OUTPUT
     - name: Slack Notification
       uses: rtCamp/action-slack-notify@v2      
       if: always()
       env:
        SLACK_CHANNEL: cypressautomation
        SLACK_COLOR: ${{ job.status }} 
        SLACK_TITLE: Appium Tests Results
        SLACK_USERNAME: testuser
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_MESSAGE: "Appium Job Status: ${{ needs.run-appium-tests.result }} "
        
   