name: BackstopJS Visual Regression Tests

on:
  workflow_dispatch:
    inputs:
      mode:
        description: 'Run mode (test or approve)'
        required: true
        default: 'test'
        type: choice
        options:
          - test
          - approve
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  backstop:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Fetch backstop-references branch
        run: |
          git fetch origin
          git checkout backstop-references || git checkout -b backstop-references
          git pull origin backstop-references || echo "Branch already up-to-date"

      - name: Ensure bitmaps_reference and bitmaps_test directories exist
        run: |
          mkdir -p backstop_data/bitmaps_reference
          mkdir -p backstop_data/bitmaps_test

      - name: Set mode
        id: set-mode
        run: echo "INPUT_MODE=${{ github.event.inputs.mode || 'test' }}" >> $GITHUB_ENV

      - name: Run BackstopJS tests
        run: |
          if [ "$INPUT_MODE" = "approve" ]; then
            echo "Approving screenshots."
            npx backstop approve
          else
            echo "Running BackstopJS tests."
            npx backstop test
          fi
        env:
          INPUT_MODE: ${{ env.INPUT_MODE }}

      - name: Commit and push approved reference images (if approve mode)
        if: always() && env.INPUT_MODE == 'approve'
        run: |
          if [ "$INPUT_MODE" = "approve" ]; then
            echo "Approving screenshots by copying them to reference folder."
            # Copy test screenshots directly to reference folder
            cp -r backstop_data/bitmaps_test/* backstop_data/bitmaps_reference/
            echo "Screenshots approved and updated."
          else
            echo "Not in approve mode. Skipping approval."
          fi

      - name: Commit and push test screenshots (if test mode)
        if: always() && env.INPUT_MODE == 'test'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # Create and checkout the branch (force update if it already exists)
          git checkout -B update-backstop-test

          # Fetch the latest from origin
          git fetch origin

          # Add and commit changes
          git add backstop_data/bitmaps_test/
          git commit -m "Save BackstopJS test screenshots" || echo "No changes to commit"

          # Force push changes to the remote branch
          git push origin update-backstop-test --force

      # Steps to prepare and deploy the report
      - name: Create .nojekyll file
        run: echo > backstop_data/html_report/.nojekyll
        if: always()

      - name: Copy latest report to a static file name
        run: cp backstop_data/html_report/*.html backstop_data/html_report/latest-report.html
        if: always() && env.INPUT_MODE == 'test'

      - name: Prepare Deployment Folder
        if: always() && env.INPUT_MODE == 'test'
        run: |
          mkdir -p backstop-reports
          cp -r backstop_data/html_report backstop-reports/html

      - name: Deploy BackstopJS Report to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        if: always()
        with:
          folder: backstop-reports
          token: ${{ secrets.GITHUB_TOKEN }}
          target-folder: backstop-reports