name: BackstopJS Visual Regression Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  backstop:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Pull reference images from backstop-references branch
        run: |
          git fetch origin backstop-references
          git checkout origin/backstop-references -- backstop_data/bitmaps_reference/

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      # - name: Run BackstopJS tests or approve step
      #   run: |
      #     if [ "{{ inputs.mode }}" = "approve" ]; then
      #       npx backstop approve
      #     else
      #       npx backstop test
      #     fi
      - name: Run BackstopJS tests
        run: |
         if [ "$INPUT_MODE" = "approve" ]; then
          npx backstop approve
         else
          npx backstop test
         fi
        env:
         INPUT_MODE: inputs.mode 


      - name: Commit and push approved reference images (if approve mode)
        if: inputs.mode == 'approve' 
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b update-backstop-references
          git add backstop_data/bitmaps_reference/
          git commit -m "Update BackstopJS reference images"
          git push origin update-backstop-references:backstop-references

      - name: Archive BackstopJS reports
        uses: actions/upload-artifact@v3
        with:
          name: backstop-data
          path: backstop_data/html_report

  deploy:
    runs-on: ubuntu-latest
    needs: backstop

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download Backstop report artifact
        uses: actions/download-artifact@v3
        with:
          name: backstop-data

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: backstop_data/html_report
