name: Run Validators

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:
  schedule:
   - cron: '0 0 * * 1'

jobs:
  run-validators:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'  # Specify the version you need

      # Step 3: Install dependencies in HTMLValidator directory
      - name: Install dependencies
        run: |
          cd HTMLValidator
          npm install

      # Step 4: Run validator.js using bash command after navigating to HTMLValidator directory
      - name: Run Default Validator
        run: bash -c "cd HTMLValidator && node validator_default.js"

      # Step 5: Run validator_WHATWG.js using bash command after navigating to HTMLValidator directory
      - name: Run WHATWG Validator
        run: bash -c "cd HTMLValidator && node validator_WHATWG.js"

      # Step 6: List all files to verify creation
      - name: List all files in HTMLValidator directory
        run: ls -R HTMLValidator

      # Step 7: Upload the generated reports as artifacts (optional)
      - name: Upload Reports
        uses: actions/upload-artifact@v4
        with:
          name: validation-reports
          path: |
            HTMLValidator/logs/*.json
            HTMLValidator/*.html
          retention-days: 2

  send-slack-notification:
   needs: [run-validators] # Wait for both cypress-run and performance-tests to complete
   if: always() # Always run the Slack notification job regardless of the status of previous jobs
   runs-on: ubuntu-latest
   name: Send Slack Notification
   steps:
     - name: Slack Notification
       uses: rtCamp/action-slack-notify@v2      
       if: always()
       env:
        SLACK_CHANNEL: cypressautomation
        SLACK_COLOR: ${{ needs.run-validators.result == 'success' && 'good' || 'danger' }}    
        SLACK_TITLE: HTML Validation Results
        SLACK_USERNAME: testuser
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_MESSAGE: "HTML Validation Job Status: ${{ needs.run-validators.result }} "