name: Cypress Artifacts
on: 
 push:
  branches:
   - main
jobs:
 cypress-run:
   runs-on: ubuntu-latest
   name: Test Artifacts
   steps:
     - uses: actions/checkout@v3 
     - uses: cypress-io/github-action@v4
     - uses: actions/upload-artifact@v3
       if: always()
       with:
         name: cypress-execution-report
         path: cypress/reports/html
     - uses: actions/upload-artifact@v3
       if: failure()
       with:
         name: cypress-screenshots
         path: cypress/screenshots
     - uses: actions/upload-artifact@v3
       if: always()
       with:
         name: cypress-videos
         path: cypress/videos
     - name : Deploy to Github pages
       uses : peaceiris/actions-gh-pages@v3
       with:
         github_token: ${{secrets.GITHUB_TOKEN}}
         publish_dir: cypress/reports/html
         publish_branch: gh-pages
         publish_dir_prefix: my-report
        
     
        
