name: Cypress Artifacts
on: 
 push:
  branches:
   - main
permissions:
 contents: write
 pages: write
 id-token: write
jobs:
 cypress-run:
   runs-on: ubuntu-latest
   name: Test Artifacts
   steps:
     - name: Actions Checkout
       uses: actions/checkout@v3 
     - name: Cypress Checkout
       uses: cypress-io/github-action@v4
     - name: Upload tests report
       uses: actions/upload-artifact@master
       if: always()
       with:
         name: cypress-execution-report
         path: cypress/reports/html
     - name: Upload tests screenshots
       uses: actions/upload-artifact@v3
       if: failure()
       with:
         name: cypress-screenshots
         path: cypress/screenshots
     - name: Upload tests videos
       uses: actions/upload-artifact@v3
       if: always()
       with:
         name: cypress-videos
         path: cypress/videos
     - name : Deploy to Github Pages
       uses: JamesIves/github-pages-deploy-action@v4
       if: always()
       with:
          folder: cypress/reports/html 
          token: ${{ secrets.GITHUB_TOKEN }}
     - name : Slack Notification
       uses: rtCamp/action-slack-notify@v2
       if: always()
       env:
        SLACK_CHANNEL: cypressautomation
        SLACK_COLOR: ${{ job.status }} 
        SLACK_MESSAGE: 'New Changes :rocket:'
        SLACK_TITLE: Regression Test
        SLACK_USERNAME: testuser
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}               
 
