name: Cypress Artifacts
on: 
 push:
  branches:
   - main
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
 cypress-run:
   runs-on: ubuntu-latest
   name: Test Artifacts
   steps:
     - uses: actions/checkout@v3 
     - uses: cypress-io/github-action@v4
     - uses: actions/upload-artifact@v3
       if: always()
       with:
         name: cypress-execution-report
         path: cypress/reports/html
     - name: Upload test screenshots
       uses: actions/upload-artifact@v3
       if: failure()
       with:
         name: cypress-screenshots
         path: cypress/screenshots
     - name: Upload test videos
       uses: actions/upload-artifact@v3
       if: always()
       with:
         name: cypress-videos
         path: cypress/videos
     - name : Deploy to Github pages
       uses : peaceiris/actions-gh-pages@v3
       with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
         publish_dir: cypress/reports/html
         publish_branch: gh-pages
         
 deploy:
   name: github-pages
   runs-on: ubuntu-latest
   needs: cypress-run
   permissions: 
    id-token: write
   env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
   steps:
     - name: Deploy to GitHub Pages
       id: deployment
       uses: actions/deploy-pages@v2
       with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_dir: cypress/reports/html
        publish_branch: gh-pages
