name: Cypress Artifacts
on: [push]
jobs:
 cypress-run:
   runs-on: ubuntu-latest
   name: Test Artifacts
   steps:
     - uses: actions/checkout@v2
     - uses: cypress-io/github-action@v4
     - uses: actions/upload-artifact@v3
       if: always()
       with:
         name: cypress-execution-report
         path: cypress/reports/html
     - uses: actions/upload-artifact@v3
       if: failure()
       with:
         name: cypress-screenshots
         path: cypress/screenshots
     - uses: actions/upload-artifact@v3
       if: always()
       with:
         name: cypress-videos
         path: cypress/videos
        
